### PR TITLE
added messaging

### PR DESCRIPTION
**Pull request by alanpoon**
#2
Repo to test this is https://github.com/alanpoon/qq_party
Currently, unable to get response.

### CODE REVIEW

**Comment by autodidaddict** [comment]
There's a couple reasons you're not getting a response. Mostly it's because the widl file doesn't include a function called `DeliverMessage`, which is the operation name used by messaging providers to deliver messages to actors. Both request and publish are functions that are only invoked by actors.

Widl doesn't really make for an easy way to label which direction message flow happens.

**Comment by autodidaddict** [comment]
Once I get back from vacation I'll go fix the `messaging.widl` so that it accurately reflects both directions of the message broker conversation.

**Comment by autodidaddict** [comment]
@alanpoon if you pull from main you'll get the newest `messaging.widl` and so your generated wrapper should have all the operations.

**Comment by brooksmtownsend** [comment]
@alanpoon We recently changed our project structure in this repo, because of this there are going to be a few conflicting files. You're welcome to take a stab at resolving those, otherwise I'd be happy to just move the files around to get this in.

**Comment by brooksmtownsend** [comment]
Unfortunately, the conflicts are too complicated to do over the GH website, I've opened up #39 with these changes and fixed merge conflicts. Closing this in favor of that PR

**Pull request closed without merging**
