### PR TITLE
TinyGo Logging Actor Abstraction

### PR DESCRIPTION
**Pull request by jordan-rash**
Included a test script that I have successfully been using locally.

### CODE REVIEW

**Review by brooksmtownsend — APPROVED** [review]
Looks awesome, thanks for adding that example in the README too 😄

**Review by brooksmtownsend — CHANGES_REQUESTED** [review]
Whoops I take it back, @jordan-rash could you add in the pkg.go.dev badge in the README for the logging interface for tinygo? It may not populate correctly yet since this isn't merged, but then the README should update when this is in `main`

**Comment by brooksmtownsend** [comment]
Should be something like:
`[GitHub go.mod Go version (subdirectory of monorepo)](https://pkg.go.dev/github.com/wasmcloud/actor-interfaces/logging/go)`

**Comment by jordan-rash** [comment]
YES SIR!!

**Comment by autodidaddict** [comment]
Pkg.go.dev will update when you follow the link and find it not there, you can then hit the "requesr" button and the site then generates the docs

**Comment by jordan-rash** [comment]
Should be G2G now

**Review by brooksmtownsend — APPROVED** [review]

**Pull request merged**
