### PR TITLE
Update control_interface.widl

### PR DESCRIPTION
**Pull request by autodidaddict**

### CODE REVIEW

**Comment by brooksmtownsend** [comment]
Quick thought here, should this `widl` or the lattice events `widl` even live in this repository anymore? I think if all of the generated code is located over in `wasmcloud-host` we can probably remove them from here 🙂 @autodidaddict

**Comment by autodidaddict** [comment]
One thing at a time ;) If we agree that this is the right schema, then we can move this stuff around afterward.

**Comment by autodidaddict** [comment]
But I agree, these two widls should probably be in `wasmCloud/wasmcloud/schemas`

**Review by brooksmtownsend — APPROVED** [review]

**Comment by brooksmtownsend** [comment]
Unsure why the checks aren't running here 🤔

**Comment by autodidaddict** [comment]
Closing this because I've moved the two schema files into the wasmcloud crate. Just need a separate PR to delete the schemas directory.

**Pull request closed without merging**
